config/routes.rb
Rails.application.routes.draw do
  get 'authors/index'
  get 'genres/index'
  get 'books/index'
  get 'books/create'
  get 'books/new'
  get 'books/edit'
  get 'books/update'
  get 'books/destroy'
resources :books, only: [:index, :new, :show, :create, :update, :detroy]
resources :authors, only: [:index]
resources :genres, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :genres, through: :books
   
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  validates :name, presence: true, uniqueness: true
    
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
    has_many :authors, through: :books
    validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def create
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private 

  def book_params
    params.require(:book).permit(:title, :author, :genre)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<% @authors.each do |author| %>
    <h2><%= author.name %></h2>
    <%= render partial: 'books/all_books', locals: {books: author.books} %>
<% end %>

app/views/books/_all_books.html.erb
<table border="1px">
    <tr>
	<th>Title</th>
	<th>Author</th>
	<th>Genre</th>
    </tr>
    <%= render partial: 'books/book', collection: books %>
</table>

app/views/books/_book.html.erb
<tr>
    <td><%= book.title %></td>
    <td><%= book.author.name %></td>
    <td><%= book.genre.name %></td>
</tr>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>
<table border="1px">
<tr>
    <th>Title</th>
    <th>Author</th>
    <th>Genre</th>
</tr>
    <%= render partial: 'book', collection: @books %>
</table>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/genres/index.html.erb
<h1>Genres</h1>

<% @genres.each do |genre| %>
    <h2><%= genre.name %></h2>
    <%= render partial: 'books/all_books', locals: {books: genre.books} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartialsLayouts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  <style>
    table {
      table-layout: fixed ;
       width: 100% ;
      
      }
    td {
        width: 25% ;
      }
  </style>
  </head>

  <body>
    <nav>
      <%= link_to :authors, authors_path %>
      <%= link_to :genres, genres_path %>
      <%= link_to :books, books_path %>
    </nav>
    <%= yield %>
  </body>
</html>